#
# Depixa Lifesteal
#

# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
heart-item: 'NETHER_STAR'

# Maximum amount of hearts a player can have.
# If a player is at max hearts, kills will drop a heart instead of directly giving it to the player.
# Set to 0 to disable. This value must be an integer.
max-hearts: 0

# This setting allows players to revive an eliminated player by transferring hearts to them.
allow-transfer-revive: true

# This setting controls whether hearts will drop on a non-player kill death. (cactus, fall damage, mobs, etc)
drop-hearts-on-death: true

# Sets the amount of hearts a player loses when they die.
# Default value: 1
hearts-lost-on-death: 1

# How long a player is banned (eliminated) for in seconds.
# 24 hours: 86400
# Set to 0 to disable.
ban-length: 0

# Allows other players to view how many hearts a certain player has.
# If disabled, only people with the permission dls.viewhearts can use it.
# Command: /viewhearts <player>
view-other-players-hearts: false

# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# 1 | 2 | 3
# 4 | 5 | 6
# 7 | 8 | 9
heart-recipe:
  1: 'NETHERITE_INGOT'
  2: 'DIAMOND_BLOCK'
  3: 'NETHERITE_INGOT'
  4: 'DIAMOND_BLOCK'
  5: 'OBSIDIAN'
  6: 'DIAMOND_BLOCK'
  7: 'NETHERITE_INGOT'
  8: 'DIAMOND_BLOCK'
  9: 'NETHERITE_INGOT'

# This is not the same as plugin version.
# Do not touch this value.
version: 0.6