name: Depixa-Lifesteal
version: 1.0.8
author: Klxzz
main: gq.depixa.lifesteal.Main
api-version: 1.17
commands:
  withdraw:
    description: Withdraw an amount of hearts.
    usage: /<command> <integer>
  lifesteal:
    description: Main command.
    aliases: [ls]
    usage: /<command> [reload]
  eliminate:
    description: Eliminates a player.
    usage: /<command> <player>
    permission: dls.eliminate
  giveheartitems:
    aliases: [givehearts, giveheartitem, giveheart]
    description: Gives heart items to a player.
    usage: /<command> <player> <amount>
    permission: dls.give
  resethealth:
    description: Reset a player's health back to 10 hearts.
    aliases: [resethp]
    usage: /<command> <player>
    permission: dls.reset
  revive:
    description: Revives an eliminated player.
    usage: /<command> <all | player>
    permission: dls.revive
  transfer:
    aliases: [givehp, transferhp, transferhearts]
    description: Transfers hearts to another player.
    usage: /<command> <player> <amount>
  viewhearts:
    description: View how many hearts another player has.
    usage: /<command> <player>